@echo off
rem Rebuild 67.exe and 67-Settings.exe from src\*.cs
setlocal
cd /d "%~dp0"

set "CSC=%WINDIR%\Microsoft.NET\Framework64\v4.0.30319\csc.exe"
if not exist "%CSC%" set "CSC=%WINDIR%\Microsoft.NET\Framework\v4.0.30319\csc.exe"
if not exist "%CSC%" (
    echo [!] C# compiler not found - .NET Framework 4.x is required.
    exit /b 1
)

set "WPF=%WINDIR%\Microsoft.NET\Framework64\v4.0.30319\WPF"

rem --- fresh build stamp so every build has a unique hash --------------------
> "src\BuildInfo.cs" echo // Generated by build.cmd - do not edit.
>> "src\BuildInfo.cs" echo namespace Popup67
>> "src\BuildInfo.cs" echo {
>> "src\BuildInfo.cs" echo     internal static class BuildInfo
>> "src\BuildInfo.cs" echo     {
>> "src\BuildInfo.cs" echo         public const string Stamp = "b%RANDOM%-%RANDOM%-%RANDOM%";
>> "src\BuildInfo.cs" echo     }
>> "src\BuildInfo.cs" echo }

rem --- main show -------------------------------------------------------------
"%CSC%" /nologo /target:winexe /optimize+ /codepage:65001 ^
    /win32icon:"src\67.ico" /out:"67.exe" ^
    /r:"%WPF%\PresentationCore.dll" /r:"%WPF%\WindowsBase.dll" ^
    "src\Util.cs" "src\Render.cs" "src\Layout.cs" "src\Windows.cs" ^
    "src\Dpi.cs" "src\Display.cs" "src\Giant.cs" "src\Director.cs" ^
    "src\Sound.cs" "src\Fx.cs" ^
    "src\BuildInfo.cs" "src\Program.cs"
if errorlevel 1 (
    echo [!] build of 67.exe failed
    exit /b 1
)
echo [ok] 67.exe rebuilt

rem --- settings app ----------------------------------------------------------
"%CSC%" /nologo /target:winexe /optimize+ /codepage:65001 ^
    /win32icon:"src\67.ico" /out:"67-Settings.exe" ^
    "src\Util.cs" "src\Dpi.cs" "src\Display.cs" "src\Render.cs" "src\Layout.cs" ^
    "src\BuildInfo.cs" "src\Settings.cs"
if errorlevel 1 (
    echo [!] build of 67-Settings.exe failed
    exit /b 1
)
echo [ok] 67-Settings.exe rebuilt

endlocal
